version: '3.1'
services:
  restapi:
    build: ./
    command: ./wait.sh restapi ./restapi
    ports:
      - 8081:8081
    depends_on:
      - postgres
    environment:
      PWDPG: "123"
  postgres:
    image: postgres:latest
    volumes:
      - ./.database/postgres/data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: "users_inf"
      POSTGRES_USER: "root"
      POSTGRES_PASSWORD: "123"
      PGDATA: "/var/lib/postgresql/data/pgdata"
    ports:
      - "5432:5432"

