version: '3.1'
services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: "users_inf"
      POSTGRES_USER: "root"
      POSTGRES_PASSWORD: "123"
      PGDATA: "/var/lib/postgresql/data/pgdata"
    ports:
      - "5432:5432"
